create schema if not exists ag_tournament;

create table if not exists ag_tournament.tournament_user_assignments (
  id bigint generated by default as identity primary key,
  tournament_id uuid not null,
  academy_id integer,
  user_id integer not null,
  created_by integer,
  created_at timestamp without time zone not null default now()
);

create unique index if not exists ag_tournament_tournament_user_assignments_tournament_user_idx
  on ag_tournament.tournament_user_assignments (tournament_id, user_id);

create index if not exists ag_tournament_tournament_user_assignments_tournament_idx
  on ag_tournament.tournament_user_assignments (tournament_id);

create index if not exists ag_tournament_tournament_user_assignments_user_idx
  on ag_tournament.tournament_user_assignments (user_id);

create index if not exists ag_tournament_tournament_user_assignments_academy_idx
  on ag_tournament.tournament_user_assignments (academy_id);

do $$
begin
  if to_regclass('public.tournament_user_assignments') is not null then
    insert into ag_tournament.tournament_user_assignments (
      tournament_id,
      academy_id,
      user_id,
      created_by,
      created_at
    )
    select
      source.tournament_id,
      source.academy_id,
      source.user_id,
      source.created_by,
      coalesce(source.created_at, now())
    from public.tournament_user_assignments source
    on conflict (tournament_id, user_id) do nothing;
  end if;
end $$;
