create table if not exists public.tournament_user_assignments (
  id bigint generated by default as identity primary key,
  tournament_id uuid not null,
  academy_id integer,
  user_id integer not null,
  created_by integer,
  created_at timestamp without time zone not null default now()
);

create unique index if not exists tournament_user_assignments_tournament_user_idx
  on public.tournament_user_assignments (tournament_id, user_id);

create index if not exists tournament_user_assignments_tournament_idx
  on public.tournament_user_assignments (tournament_id);

create index if not exists tournament_user_assignments_user_idx
  on public.tournament_user_assignments (user_id);

create index if not exists tournament_user_assignments_academy_idx
  on public.tournament_user_assignments (academy_id);
